PointAt point constraint
SleipnirGroup/TrajoptLib pull request #140
Opened 2024-04-02 10:49 UTC by bruingineer

2024-04-02 11:10 UTC, spacey-sooty commented on src/optimization/HolonomicTrajoptUtil.inc
> +// #include <sleipnir/autodiff/Variable.hpp>
Remove comment

2024-04-02 11:10 UTC, spacey-sooty commented on src/optimization/HolonomicTrajoptUtil.inc
> +    // angleDiff = atan2(sin(angleDiff), cos(angleDiff));
Is this needed?

2024-04-02 11:10 UTC, spacey-sooty commented on src/optimization/SleipnirOpti.h
> +  friend SleipnirExpr atan2(const SleipnirExpr& a, const SleipnirExpr& b);
this appears to be unused

2024-04-02 16:51 UTC, calcmogul requested changes

2024-04-02 16:51 UTC, calcmogul commented on src/optimization/HolonomicTrajoptUtil.inc
> +    auto uy = dy / sqrt(dx*dx + dy*dy);
You can use hypot(dx, dy) here instead of sqrt(dx² + dy²), which has a more efficient and numerically stable autodiff implementation.

2024-04-03 00:35 UTC, bruingineer commented
updated per comments

2024-04-03 01:39 UTC, calcmogul requested changes

2024-04-03 01:39 UTC, calcmogul commented on src/optimization/HolonomicTrajoptUtil.inc
> +#include "SleipnirOpti.h"
Is this include used?

2024-04-03 01:39 UTC, calcmogul commented on src/lib.rs
> +pub use ffi::SwerveModule;
Add a newline to the end of the file.

2024-04-03 19:39 UTC, calcmogul approved these changes

2024-04-03 19:39 UTC, merged