Add units to doc comments
SleipnirGroup/TrajoptLib pull request #151
Opened 2024-04-23 02:30 UTC by bruingineer

2024-04-23 03:29 UTC, spacey-sooty approved these changes

2024-05-21 02:42 UTC, calcmogul requested changes

2024-05-21 02:42 UTC, calcmogul commented on include/trajopt/drivetrain/SwerveDrivetrain.h
> +  /// the moment of inertial of the robot about the origin (kg * meters^2)
```suggestion
  /// the moment of inertial of the robot about the origin (kg−m²)
```

2024-05-21 02:42 UTC, calcmogul commented on include/trajopt/drivetrain/SwerveModule.h
> +   * @brief maximum torque (N*m) applied to wheel
```suggestion
   * @brief maximum torque (N−m) applied to wheel
```

2024-05-21 05:55 UTC, calcmogul approved these changes

2024-05-21 05:55 UTC, merged