Feature/iteration callback cancel
SleipnirGroup/TrajoptLib pull request #62
Opened 2023-11-15 07:43 UTC by shueja

2023-11-15 22:09 UTC, calcmogul requested changes

2023-11-15 22:09 UTC, calcmogul commented on include/trajopt/path/SwervePathBuilder.h
> +  void CancelAll();
Put an empty line between functions so it's clear which doxygen comment belongs to which.

2023-11-15 22:09 UTC, calcmogul commented on include/trajopt/cancellation/Cancellation.h
> +#pragma once
```suggestion
#pragma once

```

2023-11-15 22:09 UTC, calcmogul commented on include/trajopt/cancellation/Cancellation.h
> +}  // namespace trajopt
```suggestion
namespace trajopt {

std::atomic<int>& GetCancellationFlag();

}  // namespace trajopt
```

2023-11-15 22:09 UTC, calcmogul commented on src/optimization/Cancellation.cpp
> +}  // namespace trajopt
```suggestion
namespace trajopt {

std::atomic<int>& GetCancellationFlag() {
  static std::atomic<int> flag{0};
  return flag;
}

}  // namespace trajopt
```

2023-11-15 22:09 UTC, calcmogul commented on src/optimization/CasADiIterCallback.h
> +  ~CasADiIterCallback() override {}
```suggestion
  ~CasADiIterCallback() override = default;
```

2023-11-15 22:17 UTC, jlbabilino commented on include/trajopt/cancellation/Cancellation.h
Is this supposed to be in the public API?

2023-11-15 22:20 UTC, shueja commented on include/trajopt/cancellation/Cancellation.h
No, that was a holdover from when I used it directly in the Rust bindings, but the std::atomic can't exit the DLL anyway, so that didn't work anyway.

2023-11-16 03:58 UTC, calcmogul approved these changes

2023-11-16 04:00 UTC, merged