Rust control interval plumbing
SleipnirGroup/TrajoptLib pull request #63
Opened 2023-11-15 17:24 UTC by Lewis-Seiden

taken from https://github.com/SleipnirGroup/TrajoptLib/pull/58

2023-11-15 21:11 UTC, shueja approved these changes
Trajoptlib side looks good.

2023-11-15 21:11 UTC, shueja commented on CMakeFiles/cmake.check_cache
I don't know if committing this file will break things...probably indicates a .gitignore change needed in a later pr.

2023-11-15 22:12 UTC, calcmogul commented on CMakeFiles/cmake.check_cache
This shouldn't have been possible in the first place, due to this part of CMakeLists.txt:
```cmake
# Disable in-source builds to prevent source tree corruption
if ("${CMAKE_CURRENT_SOURCE_DIR}" STREQUAL "${CMAKE_CURRENT_BINARY_DIR}")
  message(FATAL_ERROR "
FATAL: In-source builds are not allowed.
       You should create a separate directory for build files.
")
endif()
```

2023-11-15 22:12 UTC, calcmogul commented on CMakeFiles/cmake.check_cache
Just delete the CMakeFiles folder, because it would normally already be covered by the build folder in .gitignore.

2023-11-15 22:16 UTC, calcmogul requested changes
Delete the CMakeFiles folder.

2023-11-16 03:49 UTC, calcmogul approved these changes

2023-11-16 03:50 UTC, merged